#include "Numeric.h"

namespace uut
{
	UUT_NUMERIC_IMPLEMENT(Int8) {}
	UUT_NUMERIC_IMPLEMENT(UInt8) {}
	UUT_NUMERIC_IMPLEMENT(Int16) {}
	UUT_NUMERIC_IMPLEMENT(UInt16) {}
	UUT_NUMERIC_IMPLEMENT(Int32) {}
	UUT_NUMERIC_IMPLEMENT(UInt32) {}
	UUT_NUMERIC_IMPLEMENT(Int64) {}
	UUT_NUMERIC_IMPLEMENT(UInt64) {}
}