#include "Numeric.h"

namespace uut
{
// 	UUT_NUMERIC_IMPLEMENT(Int8);
// 	UUT_NUMERIC_IMPLEMENT(UInt8);
// 	UUT_NUMERIC_IMPLEMENT(Int16);
// 	UUT_NUMERIC_IMPLEMENT(UInt16);
// 	UUT_NUMERIC_IMPLEMENT(Int32);
// 	UUT_NUMERIC_IMPLEMENT(UInt32);
// 	UUT_NUMERIC_IMPLEMENT(Int64);
// 	UUT_NUMERIC_IMPLEMENT(UInt64);
// 	UUT_NUMERIC_IMPLEMENT(Float);
// 	UUT_NUMERIC_IMPLEMENT(Double);

	UUT_NUMERIC_IMPLEMENT(bool) {}
	UUT_NUMERIC_IMPLEMENT(int8_t) {}
	UUT_NUMERIC_IMPLEMENT(uint8_t) {}
	UUT_NUMERIC_IMPLEMENT(int16_t) {}
	UUT_NUMERIC_IMPLEMENT(uint16_t) {}
	UUT_NUMERIC_IMPLEMENT(int32_t) {}
	UUT_NUMERIC_IMPLEMENT(uint32_t) {}
	UUT_NUMERIC_IMPLEMENT(int64_t) {}
	UUT_NUMERIC_IMPLEMENT(uint64_t) {}
	UUT_NUMERIC_IMPLEMENT(float) {}
	UUT_NUMERIC_IMPLEMENT(double) {}
}